### ISSUE TITLE
RuntimeError: output with shape [1, 4096, 77] doesn't match the broadcast shape [4, 4096, 77]

### ISSUE THREAD

**Issue by ScottishFold007** [tfernd/sd-fused#4]
![image](https://user-images.githubusercontent.com/36957508/197349876-2ee533ca-3f73-4700-a1cc-69550b2dd5df.png)

**Comment by tfernd** [comment]
Opps again. Forgot to duplicate context-weights for the number of heads in the attention... It worked in previous tests before due to broadcasting.

Tested now with batch-size of 8 and no low-ram mode.
I'll create new branches for some experimental stuff, didn't expect some code tyding up endup breaking things.
