### ISSUE TITLE
[not an issue] feedback

### ISSUE THREAD

**Issue by ghost** [tfernd/sd-fused#6]
Thanks for this library! It works just fine on my RX6700XT with ROCM PyTorch installed, and with ToMe enabled it gives speeds similar to other implementations (that don't have it). 

I wonder if it's feasible to try to add cross attention like in https://github.com/Doggettx/stable-diffusion (I think it's different from the "original" split attention)? Because with just that optimization with auto's webui (which doesn't really have any other optimizations for my GPU) I'm getting the same speed as with your code. It's also implemented in auto's web ui but that repo doesn't have a license, so using code from it wouldn't really be possible.

I've also checked Birch-san's SD fork with ToMe implemented, and it also gives similar speeds to having this Doggettx's split attention, so maybe it's possible to combine the two. 

I know this isn't really relevant for modern NVIDIA GPUs as they have xformers, but I think it'd still be nice for older NVIDIA GPUs and AMD GPUs :)

**Comment by ghost** [comment]
Also maybe you can check out some newer samplers that work for SD, e.g. https://github.com/LuChengTHU/dpm-solver which can give results similar to Heun but at lower steps

**Comment by tfernd** [comment]
Thanks for the feedback.
Doggettx's [split-attention](https://github.com/Doggettx/stable-diffusion/blob/main/ldm/modules/attention.py#L208) is indeed different. It uses chunks in the sequence instead of the batch as in the "original" one.

I've updated the code. Now the [chunked_attention](https://github.com/tfernd/sd-fused/blob/master/sd_fused/layers/blocks/attention/fn/chunked_attention.py) takes an additional parameter, `chunk_type`, which can be `batch` or `sequence`. So you can use either definition if you want.
`pipeline.split_attention("auto", "sequence" | "batch")` 

> I've also checked Birch-san's SD fork with ToMe implemented, and it also gives similar speeds to having this Doggettx's split attention, so maybe it's possible to combine the two.

You can try using both: `pipeline.tome(r)`. They are not mutually exclusive.

> Also maybe you can check out some newer samplers that work for SD, e.g. https://github.com/LuChengTHU/dpm-solver which can give results similar to Heun but at lower steps

I'm in the process of implementing new schedulers and trying to make them more uniform and also making the code looks readable, which is the ultimate goal :)

**Comment by ghost** [comment]
Closing to not hog up open issues :)
